name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Jekyll site
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./       # root folder
        destination: ./_site

    - name: Upload _site
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-pages-artifact@v1
        with:
          path: ./_site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
